/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-03 11:25:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.decorators.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import UrlUtil.urlUtil;

public final class navigation_002dbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624779096264L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/Desktop/CRM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DuAnCRM/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("UrlUtil.urlUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"page__header mb-0\">\r\n");
      out.write("    <div class=\"container page__container\">\r\n");
      out.write("        <div class=\"navbar navbar-secondary navbar-light navbar-expand-sm p-0\">\r\n");
      out.write("            <button class=\"navbar-toggler navbar-toggler-right\" data-toggle=\"collapse\" data-target=\"#navbarsExample03\" type=\"button\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-collapse collapse\" id=\"navbarsExample03\">\r\n");
      out.write("                <ul class=\"nav navbar-nav flex\">\r\n");
      out.write("                      <li class=\"nav-item dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                        Project\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"dropdown-menu\">\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                            Manage Project\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                            Project Create Project\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                        User\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"dropdown-menu\">\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                            User List\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                           Create User\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"#\">Task</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Components</a>\r\n");
      out.write("                                    <div class=\"dropdown-menu\">\r\n");
      out.write("                                        <a class=\"dropdown-item\"href=\"");
      out.print(request.getContextPath() + urlUtil.URL_BUTTONS);
      out.write("\">Buttons</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"alerts.html\">Alerts</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"avatars.html\">Avatars</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"modals.html\">Modals</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"charts.html\">Charts</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"icons.html\">Icons</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"forms.html\">Forms</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"range-sliders.html\">Range Sliders</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"datetime.html\">Time &amp; Date</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"tables.html\">Tables</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"tabs.html\">Tabs</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"loaders.html\">Loaders</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"drag.html\">Drag &amp; Drop</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"pagination.html\">Pagination</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"vector-maps.html\">Vector Maps</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
